#dev v2
name: Deploy dev site on push
on: 
  push:
    branches: 
      - dev
      
jobs:
  web-deploy:

    name: Deploy React App Dev
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: copy .env
      run: |
<<<<<<< HEAD
          echo 'REACT_APP_BACKEND_URL = "http://dev.donremolo.site:7000"' > .env
=======
          echo 'REACT_APP_BACKEND_URL = "http://dev.donremolo.site:7000"' > .env      
>>>>>>> qa

    - name: Use Node.js 16 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: CI= npm run build
      
    - name: Create SSH key
      run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          
    - name: Deploy with rsync
      run: |
<<<<<<< HEAD
          echo "${{ secrets.OPT_SRV }}" > build/.htaccess
          rsync -rav --delete build/ ubuntu@${{ secrets.SSH_HOST }}:/var/www/dev.donremolo.site/public_html/

=======
          echo "${{ secrets.OPT_SRV }}" > build/.htaccess   
          rsync -rav --delete build/ ubuntu@${{ secrets.SSH_HOST }}:/var/www/dev.donremolo.site/public_html/
>>>>>>> qa
